---
exclude: '.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:  # Fix general file issues
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      # - id: check-merge-conflict
        files: \.py$
  - repo: https://github.com/ansible/ansible-lint.git
    rev: master
    hooks:  # Check only Ansible files
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: local
    hooks:  # Lint python files with flake8
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
