---
- name: Download hBlock executable
  become: true
  get_url:
    url: "{{ hblock_download_url }}"
    checksum: "{{ hblock_download_checksum }}"
    dest: "{{ hblock_install_dir }}"
    mode: "{{ hblock_root_only | ternary('0744', '0755') }}"
    owner: root
    group: root

- name: Create temporary hosts file using hBlock
  become: true
  command:
    argv:
      - "{{ hblock_install_dir }}/hblock"
      - "-O{{ hblock_temp_hosts }}"  # output file
  args:
    creates: "{{ hblock_temp_hosts }}"
