---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Add a test line to the hosts file to ensure it isn't overwritten
      become: true
      lineinfile:
        path: /etc/hosts
        line: '# File not overwritten'
        state: present
        insertbefore: BOF

  roles:
    - ansible-role-hblock
