---
name: Galaxy Import
on: release

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Import role to Ansible Galaxy
        env:
            GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
        run: >-
          docker run --rm geerlingguy/docker-ubuntu1804-ansible:latest
          ansible-galaxy role import
          --api-key "$GALAXY_API_KEY"
          "$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1)"
          "$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)"
