---
name: Molecule test
on: push  # yamllint disable-line rule:truthy

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 18
      matrix:
        PYTHON_VERSION:
          - '3.6'
          - '3.7'
          - '3.8'
        MOLECULE_DISTRO:
          - ubuntu1604
          - ubuntu1804
          - debian9
          - debian10
          - centos7
          - centos8

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Install Molecule dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip pipenv
          pipenv install --ignore-pipfile --deploy --system
      - name: Test with molecule
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.MOLECULE_DISTRO }}
