---
name: Molecule test
on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        PYTHON_VERSION:
          - '3.6'
          - '3.7'
          - '3.8'
        MOLECULE_DISTRO:
          - ubuntu:16.04
          - ubuntu:18.04
          - ubuntu:19
          - debian:8
          - debian:9
          - debian:10
          - centos:7
          - centos:8

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Install Molecule dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          python -m pip install --no-cache-dir molecule[docker]
      - name: Test with molecule
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.MOLECULE_DISTRO }}
